name: Daily status check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  daily:
    runs-on: ubuntu-latest

    steps:
      - name: daily check
        run: echo "Scheduled workflow running at midnight UTC"

