name: DevSecOps End To End Pipeline

on:
  workflow_dispatch:
    
jobs:
  Code-Qyality:
    uses: .github\workflows\code-quality.yml

  Secrets-Scan:
      uses: .github\workflows\secrets-scan.yml
  
  Dependency-scan:
    uses: .github\workflows\dependency-scan.yml

  Docker-scan:
    uses: github\workflows\docker-lint.yml
      
