name: Secrets as Environment Variables

on:
  workflow_dispatch:
    
jobs:
  docker-secret:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: use docker secret as env
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER}}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD}}
        run: |
          echo "DockerHub username is = $DOCKERHUB_USER"
          echo "logging to docker"