name: Practice
#trigger on every push
on:
  push:
    branches: [main]

# this is job inside workflow  
jobs:
  #this is the name of job
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: say hello from GitHub Actions
        run: echo "Hello from GitHub Actions!"