---
name: Reusable Build
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
        required: false
        default: staging
        type: string
    secrets:
      docker_token:
        required: true
    outputs:
      build_version:
        description: "Generated build version"
        value: ${{ jobs.reusable-build.outputs.build_version}}
jobs:
  reusable-build:
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.set_version.outputs.build_version}}
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: print building app_name for env
        run: echo "Building the ${{inputs.app_name}} for ${{inputs.environment}}"
      - name: docker token is set
        run: |
          if [ -n "${{secrets.docker_token}}" ]; then
              echo "Docker token is set: true"
          else 
              echo "Docker token is set: false"
          fi
      
      - name: Generate build version
        id: set_version
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          VERSION="v1.0-${SHORT_SHA}"
          echo "build_version=$VERSION" >> $GITHUB_OUTPUT
        
      - name: print build version
        run: echo "Build version is ${{ steps.set_version.outputs.build_version}}"