---
name: Reusable Build
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
        required: false
        default: staging
        type: string
    secrets:
      docker_token:
        required: true
jobs:
  reusable-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: print building app_name for env
        run: echo "Building the ${{inputs.app_name}} for ${{inputs.environment}}"
      - name: docker token is set
        run: |
          if [ -n "${{secrets.docker_token}}"]; then
              echo "Docker token is set: true"
          else 
              echo "Docker token is set: false"
          fi
