name: Secrets Message

on:
  workflow_dispatch:
    
jobs:
  secrets:
    runs-on: ubuntu-latest
  
    steps:
      - name: check secret is set or not
        run: |
          if: [ -n "${{ secrets.MY_SECRET_MESSAGE }}"]; then
            echo "secret is not set"
          else
            echo "secret is set"
          fi

      - name: print secret
        run:  echo "the secret is:" ${{ secrets.MY_SECRET_MESSAGE }}